-- MySQL Script generated by MySQL Workbench
-- 12/01/16 14:03:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema road_signs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema road_signs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `road_signs` DEFAULT CHARACTER SET utf8 ;
USE `road_signs` ;

-- -----------------------------------------------------
-- Table `road_signs`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `road_signs`.`materials` (
  `idmaterials` INT NOT NULL AUTO_INCREMENT,
  `materials_name` VARCHAR(255) NOT NULL,
  `materials_price` FLOAT NOT NULL COMMENT '//what we buy and sell',
  `materials_quantity` FLOAT NULL,
  PRIMARY KEY (`idmaterials`),
  UNIQUE INDEX `materials_name_UNIQUE` (`materials_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `road_signs`.`road_signs_catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `road_signs`.`road_signs_catalog` (
  `idroad_signs_catalog` INT NOT NULL AUTO_INCREMENT,
  `road_signs_catalog_name` VARCHAR(45) NOT NULL,
  `road_signs_catalog_price` FLOAT NOT NULL,
  `road_signs_catalog_masks` INT NULL,
  PRIMARY KEY (`idroad_signs_catalog`),
  UNIQUE INDEX `road_signs_catalog_name_UNIQUE` (`road_signs_catalog_name` ASC),
  INDEX `FK_masks_idx` (`road_signs_catalog_masks` ASC),
  CONSTRAINT `FK_masks`
    FOREIGN KEY (`road_signs_catalog_masks`)
    REFERENCES `road_signs`.`materials` (`idmaterials`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `road_signs`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `road_signs`.`customers` (
  `idcustomers` INT NOT NULL AUTO_INCREMENT,
  `customers_name` VARCHAR(255) NOT NULL,
  `customers_INN` BIGINT(10) NOT NULL,
  `customers_KPP` BIGINT(9) NOT NULL,
  PRIMARY KEY (`idcustomers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `road_signs`.`zakaz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `road_signs`.`zakaz` (
  `idzakaz` INT NOT NULL AUTO_INCREMENT,
  `zakaz_name` VARCHAR(45) NOT NULL,
  `zakaz_date` DATE NOT NULL,
  `zakaz_customer` INT NOT NULL,
  `zakaz_sum` FLOAT NOT NULL COMMENT '//zdes dolzhen byt\' SUM poziciy is \"sostav_zakaza\", sovpadauischikh po id_zakaza',
  PRIMARY KEY (`idzakaz`),
  UNIQUE INDEX `zakaz_name_UNIQUE` (`zakaz_name` ASC),
  INDEX `FK_customer_idx` (`zakaz_customer` ASC),
  CONSTRAINT `FK_customer`
    FOREIGN KEY (`zakaz_customer`)
    REFERENCES `road_signs`.`customers` (`idcustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `road_signs`.`zakaz_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `road_signs`.`zakaz_contents` (
  `idzakaz_contents` INT NOT NULL AUTO_INCREMENT,
  `zakaz_contents_idzakaza` INT NOT NULL,
  `zakaz_contents_id_road_signs` INT NULL,
  `zakaz_contents_id_materials` INT NULL,
  `zakaz_contents_quantity` INT NOT NULL,
  PRIMARY KEY (`idzakaz_contents`),
  INDEX `FK_zakaz_idx` (`zakaz_contents_idzakaza` ASC),
  INDEX `FK_road_sign_idx` (`zakaz_contents_id_road_signs` ASC),
  INDEX `FK_materials_idx` (`zakaz_contents_id_materials` ASC),
  CONSTRAINT `FK_zakaz`
    FOREIGN KEY (`zakaz_contents_idzakaza`)
    REFERENCES `road_signs`.`zakaz` (`idzakaz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_road_sign`
    FOREIGN KEY (`zakaz_contents_id_road_signs`)
    REFERENCES `road_signs`.`road_signs_catalog` (`idroad_signs_catalog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_materials`
    FOREIGN KEY (`zakaz_contents_id_materials`)
    REFERENCES `road_signs`.`materials` (`idmaterials`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `road_signs`.`materials`
-- -----------------------------------------------------
START TRANSACTION;
USE `road_signs`;
INSERT INTO `road_signs`.`materials` (`idmaterials`, `materials_name`, `materials_price`, `materials_quantity`) VALUES (1, 'SQUARE BLUE MASK', 90.00, 100);
INSERT INTO `road_signs`.`materials` (`idmaterials`, `materials_name`, `materials_price`, `materials_quantity`) VALUES (2, 'TRIANGLE WHITE MASK', 90.00, 100);
INSERT INTO `road_signs`.`materials` (`idmaterials`, `materials_name`, `materials_price`, `materials_quantity`) VALUES (3, 'ROUND BLUE MASK', 90.00, 100);
INSERT INTO `road_signs`.`materials` (`idmaterials`, `materials_name`, `materials_price`, `materials_quantity`) VALUES (4, 'PIPES 53MM', 390.00, 100);
INSERT INTO `road_signs`.`materials` (`idmaterials`, `materials_name`, `materials_price`, `materials_quantity`) VALUES (5, 'PIPES 76MM', 470.00, 100);
INSERT INTO `road_signs`.`materials` (`idmaterials`, `materials_name`, `materials_price`, `materials_quantity`) VALUES (6, 'BALLS OF STEEL', 10000.00, 100);

COMMIT;


-- -----------------------------------------------------
-- Data for table `road_signs`.`road_signs_catalog`
-- -----------------------------------------------------
START TRANSACTION;
USE `road_signs`;
INSERT INTO `road_signs`.`road_signs_catalog` (`idroad_signs_catalog`, `road_signs_catalog_name`, `road_signs_catalog_price`, `road_signs_catalog_masks`) VALUES (1, 'SQUARE BLUE SIGN 1', 1000.00, 1);
INSERT INTO `road_signs`.`road_signs_catalog` (`idroad_signs_catalog`, `road_signs_catalog_name`, `road_signs_catalog_price`, `road_signs_catalog_masks`) VALUES (2, 'SQUARE BLUE SIGN 2', 1000.00, 1);
INSERT INTO `road_signs`.`road_signs_catalog` (`idroad_signs_catalog`, `road_signs_catalog_name`, `road_signs_catalog_price`, `road_signs_catalog_masks`) VALUES (3, 'TRAINGLE WHITE SIGN', 790.00, 2);
INSERT INTO `road_signs`.`road_signs_catalog` (`idroad_signs_catalog`, `road_signs_catalog_name`, `road_signs_catalog_price`, `road_signs_catalog_masks`) VALUES (4, 'RECTANGLE RED SIGN', 1600.00, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `road_signs`.`customers`
-- -----------------------------------------------------
START TRANSACTION;
USE `road_signs`;
INSERT INTO `road_signs`.`customers` (`idcustomers`, `customers_name`, `customers_INN`, `customers_KPP`) VALUES (1, 'GAY TEST', 7200256400, 310020091);
INSERT INTO `road_signs`.`customers` (`idcustomers`, `customers_name`, `customers_INN`, `customers_KPP`) VALUES (2, 'TRUE GAY TEST', 7256891841, 859073891);
INSERT INTO `road_signs`.`customers` (`idcustomers`, `customers_name`, `customers_INN`, `customers_KPP`) VALUES (3, 'ULTIMATE GAY TEST', 3847049847, 864397643);

COMMIT;


-- -----------------------------------------------------
-- Data for table `road_signs`.`zakaz`
-- -----------------------------------------------------
START TRANSACTION;
USE `road_signs`;
INSERT INTO `road_signs`.`zakaz` (`idzakaz`, `zakaz_name`, `zakaz_date`, `zakaz_customer`, `zakaz_sum`) VALUES (1, 'T-1-16', '02.02.2016', 1, \\FUNC);
INSERT INTO `road_signs`.`zakaz` (`idzakaz`, `zakaz_name`, `zakaz_date`, `zakaz_customer`, `zakaz_sum`) VALUES (2, 'T-2-16', '03.03.2016', 2, \\FUNC);
INSERT INTO `road_signs`.`zakaz` (`idzakaz`, `zakaz_name`, `zakaz_date`, `zakaz_customer`, `zakaz_sum`) VALUES (3, 'T-3-16', '03.03.2016', 1, \\FUNC);

COMMIT;


-- -----------------------------------------------------
-- Data for table `road_signs`.`zakaz_contents`
-- -----------------------------------------------------
START TRANSACTION;
USE `road_signs`;
INSERT INTO `road_signs`.`zakaz_contents` (`idzakaz_contents`, `zakaz_contents_idzakaza`, `zakaz_contents_id_road_signs`, `zakaz_contents_id_materials`, `zakaz_contents_quantity`) VALUES (1, 1, 1, NULL, 3);
INSERT INTO `road_signs`.`zakaz_contents` (`idzakaz_contents`, `zakaz_contents_idzakaza`, `zakaz_contents_id_road_signs`, `zakaz_contents_id_materials`, `zakaz_contents_quantity`) VALUES (2, 1, 2, NULL, 2);
INSERT INTO `road_signs`.`zakaz_contents` (`idzakaz_contents`, `zakaz_contents_idzakaza`, `zakaz_contents_id_road_signs`, `zakaz_contents_id_materials`, `zakaz_contents_quantity`) VALUES (3, 1, NULL, 6, 4);

COMMIT;

